In [2]:
import pandas as pd

In [5]:
data={
    "name":["lihua","张伟","meili"],
    "age":[23,21,18],
    "sex":["male","male","female"],
}

df=pd.DataFrame(data)
df

    name  age     sex
0  lihua   23    male
1     张伟   21    male
2  meili   18  female

In [6]:
df["sex"]

0      male
1      male
2    female
Name: sex, dtype: str

In [8]:
ages=pd.Series([33,54,66,77,13,37],name="age")
ages

0    33
1    54
2    66
3    77
4    13
5    37
Name: age, dtype: int64

In [9]:
df["age"].max()

np.int64(23)

In [10]:
ages.max()

np.int64(77)

In [11]:
df.describe()

             age
count   3.000000
mean   20.666667
std     2.516611
min    18.000000
25%    19.500000
50%    21.000000
75%    22.000000
max    23.000000